# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Benachrichtigungspin',
                'verbose_name_plural': 'Benachrichtigungspins',
            },
        ),
    ]
